package org.rapla.server.spring;

import org.rapla.server.spring.oauth.external.ExternalProvidersProperties;
import org.rapla.server.spring.oauth.external.ProviderConfig;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.util.HtmlUtils;

import java.util.List;

/**
 * Replaces Spring Security's DefaultLoginPageGeneratingFilter with the ONE
 * combined rapla login page (PRD 072 Phase 1).
 *
 * <p>The page ALWAYS renders an SSO chooser — one link per
 * {@link ExternalProvidersProperties#enabledProviders()}, each pointing at
 * {@code /oauth2/authorization/<id>} (Spring's {@code oauth2Login()} kickoff).
 * The inline username/password form is OPTIONAL, gated by the
 * {@code rapla.oauth.web.password-login} flag (default ON). This is SEPARATE
 * from {@code rapla.oauth.swing-legacy-login} (Swing-only, default off).
 *
 * <p>Activated by SecurityConfig's {@code formLogin().loginPage("/login")} +
 * {@code oauth2Login().loginPage("/login")}, which disable the default
 * generators. {@code /login} (GET) renders this page; {@code /login} (POST) is
 * intercepted by Spring's UsernamePasswordAuthenticationFilter before this
 * controller sees it; the password field is NOT marked required (rapla's dev
 * admin has an empty password).
 *
 * <p>No own enforced CSP: this page is covered by the global report-only header
 * and its content is fully self-authored (no user reflection beyond the fixed
 * banner). The small inline submit-feedback script runs under the report-only
 * policy. (A hand-rolled enforced CSP here previously broke the form POST — a
 * Chrome form-action-vs-302 false-positive — and the inline style; not worth it
 * for a static page. The SPA's CSP is build-generated by Angular autoCsp.)
 */
@Controller
@RequestMapping("/login")
public class LoginPageController
{
    private final ExternalProvidersProperties externalProviders;
    private final boolean passwordLoginEnabled;

    public LoginPageController(ExternalProvidersProperties externalProviders,
                              @Value("${rapla.oauth.web.password-login:true}") boolean passwordLoginEnabled)
    {
        this.externalProviders = externalProviders;
        this.passwordLoginEnabled = passwordLoginEnabled;
    }

    @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
    @ResponseBody
    public String loginPage(@RequestParam(value = "error", required = false) String error,
                            @RequestParam(value = "logout", required = false) String logout)
    {
        String banner = "";
        if (error != null)
        {
            banner = "<p style=\"color:#c00;\">Invalid username or password</p>";
        }
        else if (logout != null)
        {
            banner = "<p style=\"color:#080;\">You have been logged out</p>";
        }
        return """
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <title>Rapla — Sign in</title>
                  <style>
                    body { font-family: system-ui, sans-serif; background: #f4f4f4; margin: 0; padding: 0; display: flex; min-height: 100vh; align-items: center; justify-content: center; }
                    .card { background: #fff; padding: 2rem 2.5rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,.08); min-width: 320px; }
                    h1 { margin: 0 0 1rem; font-size: 1.4rem; color: #333; }
                    label { display: block; margin: 0.8rem 0 0.2rem; color: #555; font-size: 0.9rem; }
                    input[type=text], input[type=password] { width: 100%; padding: 0.5rem; border: 1px solid #ccc; border-radius: 4px; font-size: 1rem; box-sizing: border-box; }
                    button { margin-top: 1.2rem; padding: 0.6rem 1.2rem; background: #2a6; color: #fff; border: 0; border-radius: 4px; cursor: pointer; font-size: 1rem; width: 100%; }
                    button:hover { background: #248; }
                    button:disabled { background: #888; cursor: default; }
                    .note { color: #888; font-size: 0.8rem; margin-top: 1rem; }
                    .remember { display: flex; align-items: center; gap: 0.5rem; margin: 1rem 0 0.2rem; color: #555; font-size: 0.9rem; }
                    .remember input { margin: 0; }
                    .sso { display: block; text-decoration: none; text-align: center; margin: 0.5rem 0; padding: 0.6rem 1.2rem; background: #345; color: #fff; border-radius: 4px; font-size: 1rem; }
                    .sso:hover { background: #234; }
                    .divider { text-align: center; color: #aaa; margin: 1.2rem 0 0.4rem; font-size: 0.8rem; }
                  </style>
                </head>
                <body>
                  <div class="card">
                    <h1>Rapla — Sign in</h1>
                    %BANNER%
                    %SSO%
                    %PASSWORD%
                  </div>
                  <script>
                    var f = document.querySelector('form');
                    if (f) {
                      f.addEventListener('submit', function () {
                        var b = document.getElementById('btn');
                        if (b) { b.disabled = true; b.textContent = 'Signing in...'; }
                      });
                    }
                  </script>
                </body>
                </html>
                """
                .replace("%BANNER%", banner)
                .replace("%SSO%", ssoButtonsHtml())
                .replace("%PASSWORD%", passwordLoginEnabled ? passwordFormHtml() : "");
    }

    private String ssoButtonsHtml()
    {
        List<ProviderConfig> providers = externalProviders == null
                ? List.of() : externalProviders.enabledProviders();
        if (providers.isEmpty())
        {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        for (ProviderConfig p : providers)
        {
            String id = HtmlUtils.htmlEscape(p.id());
            String label = HtmlUtils.htmlEscape(p.displayName());
            sb.append("<a class=\"sso\" href=\"/oauth2/authorization/")
              .append(id)
              .append("\">")
              .append(label)
              .append("</a>\n");
        }
        return sb.toString();
    }

    private String passwordFormHtml()
    {
        return """
                <div class="divider">— or —</div>
                <form method="post" action="/login">
                  <label for="u">Username</label>
                  <input id="u" type="text" name="username" autofocus required>
                  <label for="p">Password</label>
                  <input id="p" type="password" name="password">
                  <label class="remember">
                    <input type="checkbox" name="remember-me" value="on">
                    Remember me on this device
                  </label>
                  <button type="submit" id="btn">Sign in</button>
                </form>
                <p class="note">Dev default: <code>admin</code> with empty password.</p>
                """;
    }
}
