package org.rapla.server.spring.graphql;

import java.util.List;

/**
 * Single source of truth for column presentation attributes. Adding an entry here
 * automatically extends the GraphQL schema for {@code @column} AND all
 * {@code *GroupKey}/{@code *Aggregate} input types — no manual schema editing required,
 * no drift between the directive and the input fields.
 *
 * <p>{@link HotSwappableGraphQlSource} concatenates {@link #generateSdl()} into the
 * generated SDL alongside the classification and function-field fragments.
 */
public final class ColumnPresentation
{
    private ColumnPresentation() {}

    /**
     * One presentation attribute — whether it appears in the {@code @column} directive
     * args, in the {@code *GroupKey}/{@code *Aggregate} input fields, or both.
     */
    public record Attr(String name, String gqlType, String description, boolean forDirective, boolean forInput) {}

    /** The authoritative attribute list. Changing this regenerates the schema automatically. */
    public static final List<Attr> ATTRS = List.of(
            new Attr("header", "String",  "Column header label (falls back to alias/key).",       true, true),
            new Attr("order",  "Int",     "Column position left to right (lower = leftmost).",    true, true),
            new Attr("group",  "Boolean", "Mark as the row-grouping column (flat views only).",   true, false),
            new Attr("format", "String",  "Opaque date-format token, client-interpreted.",        true, false)
    );

    /** Input types that receive the {@link Attr#forInput()} attributes. */
    private static final List<String> INPUT_TYPES = List.of(
            "BlockGroupKey",       "BlockAggregate",
            "AllocatableGroupKey", "AllocatableAggregate",
            "ReservationGroupKey", "ReservationAggregate"
    );

    /**
     * GraphQL enums whose SDL is generated from the Java enum constants.
     * Adding a value to a Java enum automatically extends the schema — no drift possible.
     */
    @SuppressWarnings("rawtypes")
    private static final List<Class<? extends Enum>> VIEW_ENUMS = List.of(
            ViewRenderMode.class, ViewAnchor.class, ViewDateUnit.class
    );

    /** Generate the SDL fragment — called once at startup / schema rebuild. */
    public static String generateSdl()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("# ---- Generated by ColumnPresentation — edit Java sources, not this block ----\n");

        // View enums (ViewRenderMode, ViewAnchor, ViewDateUnit)
        for (Class<? extends Enum> e : VIEW_ENUMS)
        {
            sb.append("enum ").append(e.getSimpleName()).append(" {");
            for (Enum<?> c : e.getEnumConstants())
            {
                sb.append(' ').append(c.name());
            }
            sb.append(" }\n");
        }
        sb.append('\n');

        // @column directive
        sb.append("directive @column(");
        boolean first = true;
        for (Attr a : ATTRS)
        {
            if (!a.forDirective()) continue;
            if (!first) sb.append(", ");
            sb.append(a.name()).append(": ").append(a.gqlType());
            first = false;
        }
        sb.append(") on FIELD\n\n");

        // extend each input type with the forInput attrs
        for (String type : INPUT_TYPES)
        {
            sb.append("extend input ").append(type).append(" {\n");
            for (Attr a : ATTRS)
            {
                if (!a.forInput()) continue;
                sb.append("  \"").append(a.description()).append("\"\n");
                sb.append("  ").append(a.name()).append(": ").append(a.gqlType()).append("\n");
            }
            sb.append("}\n\n");
        }
        return sb.toString();
    }
}
