CREATE TABLE ALLOCATION ( APPOINTMENT_ID INTEGER NOT NULL, RESOURCE_ID INTEGER NOT NULL, OPTIONAL INTEGER );
CREATE INDEX KEY_ALLOCATION_APPOINTMENT ON ALLOCATION(APPOINTMENT_ID);
CREATE TABLE APPOINTMENT ( ID INTEGER NOT NULL, EVENT_ID INTEGER NOT NULL ,  APPOINTMENT_START DATETIME NOT NULL ,  APPOINTMENT_END DATETIME NOT NULL ,  REPETITION_TYPE VARCHAR(255),  REPETITION_NUMBER INTEGER ,REPETITION_END DATETIME ,  REPETITION_INTERVAL INTEGER ,  PRIMARY KEY  (ID));
CREATE INDEX KEY_APPOINTMENT_EVENT ON APPOINTMENT(EVENT_ID);
CREATE TABLE APPOINTMENT_EXCEPTION (  APPOINTMENT_ID INTEGER NOT NULL ,  EXCEPTION_DATE DATETIME NOT NULL );
CREATE INDEX KEY_APPOINTMENT_EXCEPTION_APPOINTMENT ON APPOINTMENT_EXCEPTION(APPOINTMENT_ID);
CREATE TABLE CATEGORY (  ID INTEGER NOT NULL ,  PARENT_ID INTEGER ,  CATEGORY_KEY VARCHAR(100) NOT NULL ,  LABEL VARCHAR(255) , DEFINITION LONGTEXT, PARENT_ORDER  INTEGER,PRIMARY KEY  (ID));
CREATE INDEX KEY_CATEGORY_PARENT ON CATEGORY(PARENT_ID);
CREATE TABLE DYNAMIC_TYPE (  ID INTEGER NOT NULL ,  TYPE_KEY VARCHAR(100) NOT NULL ,  DEFINITION LONGTEXT NOT NULL,  PRIMARY KEY  (ID));
CREATE TABLE EVENT (  ID INTEGER NOT NULL ,  TYPE_KEY VARCHAR(100) NOT NULL ,  OWNER_ID INTEGER NOT NULL ,  CREATION_TIME DATETIME,  LAST_CHANGED DATETIME ,LAST_CHANGED_BY INTEGER,  PRIMARY KEY  (ID));
CREATE TABLE EVENT_ATTRIBUTE_VALUE (  EVENT_ID INTEGER NOT NULL ,  ATTRIBUTE_KEY VARCHAR(100) NOT NULL ,  ATTRIBUTE_VALUE LONGTEXT);
CREATE INDEX KEY_EVENT_ATTRIBUTE_VALUE_EVENT ON EVENT_ATTRIBUTE_VALUE(EVENT_ID);
CREATE TABLE PERIOD (  ID INTEGER NOT NULL ,  NAME VARCHAR(255) NOT NULL ,  PERIOD_START DATETIME NOT NULL ,  PERIOD_END DATETIME NOT NULL ,  PRIMARY KEY  (ID));
CREATE TABLE PERMISSION (  RESOURCE_ID INTEGER NOT NULL ,  USER_ID INTEGER ,  GROUP_ID INTEGER , ACCESS_LEVEL INTEGER NOT NULL ,  MIN_ADVANCE INTEGER ,  MAX_ADVANCE INTEGER ,  START_DATE DATETIME ,  END_DATE DATETIME );
CREATE INDEX KEY_PERMISSION_RESOURCE ON PERMISSION(RESOURCE_ID)
CREATE TABLE PREFERENCE (  USER_ID INTEGER,  ROLE VARCHAR(255)  NOT NULL ,  STRING_VALUE LONGTEXT, XML_VALUE LONGTEXT);
CREATE INDEX KEY_PREFERENCE_USER ON PREFERENCE(USER_ID)
CREATE TABLE RAPLA_USER (  ID INTEGER NOT NULL ,  USERNAME VARCHAR(100)  NOT NULL ,  PASSWORD VARCHAR(255)  ,  NAME VARCHAR(255)  NOT NULL ,  EMAIL VARCHAR(255)  NOT NULL ,  ISADMIN INTEGER NOT NULL ,  PRIMARY KEY  (ID));
CREATE TABLE RAPLA_USER_GROUP ( USER_ID INTEGER NOT NULL, CATEGORY_ID INTEGER NOT NULL );
CREATE INDEX KEY_RAPLA_USER_GROUP_USER ON RAPLA_USER_GROUP(USER_ID)
CREATE TABLE RAPLA_RESOURCE (  ID INTEGER NOT NULL ,  TYPE_KEY VARCHAR(100)  NOT NULL, IGNORE_CONFLICTS INTEGER NOT NULL, OWNER_ID INTEGER, CREATION_TIME DATETIME,  LAST_CHANGED DATETIME ,LAST_CHANGED_BY INTEGER, PRIMARY KEY  (ID));
CREATE TABLE RESOURCE_ATTRIBUTE_VALUE (  RESOURCE_ID INTEGER NOT NULL ,  ATTRIBUTE_KEY VARCHAR(100),  ATTRIBUTE_VALUE LONGTEXT);
CREATE INDEX KEY_RESOURCE_ATTRIBUTE_VALUE_RESOURCE ON RESOURCE_ATTRIBUTE_VALUE(RESOURCE_ID)